[package]
name = "shesh"
version = "1.1.3"
description = "a simple shell for your terminal"
edition = "2024"
license = "GPL-3.0"
repository = "https://github.com/6z7y/shesh"

[dependencies]
libc = "^0.2.174"
nu-ansi-term = "^0.50.1"
reedline = "^0.40.0"
